<?php /** @var \Magento\Catalog\Block\Product\View $block */ ?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>

<?php /** @TODO: only logged in customers must be able to make a request. Show login form on button click */ ?>
<button class="action primary" data-mage-init='{"vitaliiLukaRegularCustomerButton":{
    "url": "<?= $escaper->escapeJs($block->getUrl('vitaliiluka_regular_customer/index/RequestProductID')) ?>",
    "productId": "<?= $escaper->escapeJs((int) $block->getProduct()->getId()) ?>"
    }}'>
    <span><?= $escaper->escapeHtml(__('Participate in the program')) ?></span>
</button>
