<?php /** @var \VitaliiLuka\RegularCustomer\Block\Product\View\DiscountRequestForm $block */ ?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>

<div style="display: none"
     class="message-success success message"
     id="vitalii-luka-regular-customer-message"
     data-mage-init='{"vitaliiLukaRegularCustomerMessage":{}}'
>
    <p><?= $escaper->escapeHtml(__('Already requested!')) ?></p>
</div>
